# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Use Node.js 14.15
        uses: actions/setup-node@v1
        with:
          node-version: '14.15'
      - run: npm ci
      - run: npm install -g less

      # Generate files
      - name: Generate css file
      - run: lessc style/theme.less gen/theme.css

      - name: Generate userCSS file
      - run: cat style/metadata.css > High-Contrast-Dark-Theme.user.css
      - run: cat style/theme.less >> High-Contrast-Dark-Theme.user.css

      - name: Generate bookmarklet
      - run: node util/converter.js

      # Save files
      - name: Commit generated files to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-generate userstyle and bookmarklet
          push_options: '--force'
